title: KDN
baseURL: "https://devops.kaldei.xyz/"
canonifyURLs: true
languageCode: en-us
theme: PaperMod
paginate: 15

params:
  # Custom variables
  acronym: KDN
  topic: DevOps
  color: "SpringGreen"

  # Parameters
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  defaultTheme: auto # Color theme (auto, light or dark)
  disableScrollToTop: true # Disable scroll to top button
  mainSections: [] # Don't display posts list on Home Page
  ShowCodeCopyButtons: true # Enable button in code block

  assets:
    favicon: images/favicon.png

# Required for markdown coloration
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      typographer: false

# Required for search bar
outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: Home
      identifier: home
      weight: 1
      url: /
    - name: Clouds
      weight: 2
      identifier: Clouds
      url: /clouds/
    - name: IaC
      weight: 3
      identifier: IaC
      url: /iac/
    - name: CI/CD
      weight: 4
      identifier: CI/CD
      url: /cicd/
    - name: Scripting
      weight: 5
      identifier: Scripting
      url: /scriptingd/
    - name: Search
      weight: 6
      identifier: search
      url: /search/
    - name: About
      weight: 7
      identifier: about
      url: /about/
